name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install cURL
      run: sudo apt-get install -y curl
    - name: Obtener nombre del repositorio
      id: obtener-nombre-repo
      run: |
        echo "::set-output name=repo_name::$(echo "${{ github.repository }}" | cut -d'/' -f2)"
    - uses: actions/checkout@v3
    - name: Call API
      run: |
          # Aquí puedes realizar la llamada a la API utilizando cURL o cualquier otra herramienta de tu elección
          body='{"ms":"${{ steps.obtener-nombre-repo.outputs.repo_name }}","hash":"${{ github.sha }}","status":"GENERATE DOCKER"}'
          
          # Realizar la llamada a la API con el cuerpo de la solicitud
          curl -X POST -H "Content-Type: application/json" -d "$body" "${{ secrets.SERVER }}"
    - name: Build the Docker image
      run: |
        docker login acrindep.azurecr.io --username ${{ secrets.USER }} -p ${{ secrets.PASSWORD }}
        docker build -t acrindep.azurecr.io/ns-sb-0001-sigebi/${{ steps.obtener-nombre-repo.outputs.repo_name }}:${{ github.sha }} .
        docker push acrindep.azurecr.io/ns-sb-0001-sigebi/${{ steps.obtener-nombre-repo.outputs.repo_name }}:${{ github.sha }}

    - name: Call API
      run: |
          # Aquí puedes realizar la llamada a la API utilizando cURL o cualquier otra herramienta de tu elección
          body='{"ms":"${{ steps.obtener-nombre-repo.outputs.repo_name }}","hash":"${{ github.sha }}"}'
          
          # Realizar la llamada a la API con el cuerpo de la solicitud
          curl -X POST -H "Content-Type: application/json" -d "$body" "${{ secrets.SERVER }}"
